version: "4"

services:
  db:
    image: bitnami/postgresql
    container_name: faf-db
    restart: always
    tty: true
    environment:
      - POSTGRESQL_USERNAME=dockerr
      - POSTGRESQL_PASSWORD=dock3rr
      - POSTGRESQL_DATABASE=fafapi
    ports: 
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U use"]
      interval: 10s
      timeout: 5s
      retries: 5